In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3]

In [3]:
np.array(mylist)

array([1, 2, 3])

In [4]:
nested_list = [[1, 2], [3, 4], [5, 6]]

In [5]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [9]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.zeros((4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
np.zeros((4, 4), int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [15]:
np.ones((4, 4), int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [23]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [30]:
np.random.rand(2)

array([0.35494922, 0.79313542])

In [32]:
np.random.rand(3, 3)

array([[0.43374349, 0.56802197, 0.59849219],
       [0.20629658, 0.501721  , 0.94763234],
       [0.89699908, 0.99192132, 0.23218689]])

In [39]:
np.random.randn(3, 2)

array([[-0.52918221,  0.45602877],
       [-1.64402763, -1.15183054],
       [-0.79662823, -0.19318936]])

In [46]:
np.random.randint(1, 100, 10)

array([63, 61, 66, 17,  5, 23, 79, 70, 39, 52], dtype=int32)

In [56]:
np.random.seed(42)
np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

In [62]:
np.random.rand(3)

array([0.43194502, 0.29122914, 0.61185289])

In [63]:
arr = np.arange(25)

In [64]:
ranarr = np.random.randint(0, 50, 10)

In [65]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [66]:
ranarr

array([41, 27, 15, 14, 46, 43,  2, 36,  6, 20], dtype=int32)

In [67]:
arr.shape

(25,)

In [73]:
arr = arr.reshape(5, 5)

In [74]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [77]:
ranarr.max()

np.int32(46)

In [78]:
ranarr.argmax()

np.int64(4)

In [80]:
ranarr.min()

np.int32(2)

In [81]:
ranarr.argmin()

np.int64(6)

In [83]:
ranarr.dtype

dtype('int32')

In [84]:
arr.dtype

dtype('int64')