In [1]:
import numpy as np

In [5]:
arr = np.arange(0,11)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[8]

np.int64(8)

In [9]:
arr[1:3]

array([1, 2])

In [10]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr[0:5] = 100

In [13]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
arr = np.arange(0,11)

In [15]:
slice_of_arr = arr[:5]

In [16]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
slice_of_arr[:] = 99

In [19]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [23]:
arr_copy = arr.copy()

In [24]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [25]:
arr_copy[:] = 0

In [26]:
arr_copy

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
arr = np.arange(0, 11)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [32]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [33]:
arr_2d[0]

array([ 5, 10, 15])

In [34]:
arr_2d.shape

(3, 3)

In [36]:
arr_2d[2][2]

np.int64(45)

In [37]:
arr_2d[0, 0]

np.int64(5)

In [39]:
arr_2d[:1, :2]

array([[ 5, 10]])

In [40]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [41]:
arr = np.arange(1, 11)

In [42]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [46]:
bool_arr = arr > 4

In [47]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [50]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])