In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 10)

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### adds 5 to every item in array

In [7]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [9]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### First item is 0/0 so that gives a warning but numpy still outputs the result with the first element being nan (nut a number)

In [12]:
arr / arr

C:\Users\sarap\AppData\Local\Temp\ipykernel_22992\2811617162.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

#### Because first element is 0 the result gives inf (infinity) as the first number and produces a RuntimeWarning but still gives an output.

In [14]:
1 / arr

C:\Users\sarap\AppData\Local\Temp\ipykernel_22992\2495778407.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

#### Gives the square root of every item

In [15]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

#### Gives the sin of every item

In [18]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

### Gives the log of every item

In [19]:
np.log(arr)

C:\Users\sarap\AppData\Local\Temp\ipykernel_22992\2931416741.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

### Gives the cos of every item

In [20]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [21]:
arr.sum()

np.int64(45)

In [22]:
arr.mean()

np.float64(4.5)

In [23]:
arr.std()

np.float64(2.8722813232690143)

In [24]:
arr.var()

np.float64(8.25)

In [28]:
array_2d = np.arange(0, 25).reshape(5, 5)

In [29]:
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### Sum all elements in array

In [31]:
array_2d.sum()

np.int64(300)

#### Sum elements in each column

In [32]:
array_2d.sum(axis=0)

array([50, 55, 60, 65, 70])

#### Sum elements in each row

In [33]:
array_2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])